export const ActionTypes = {
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    REGISTER: 'REGISTER',
    REFRESH_TOKEN: 'REFRESH_TOKEN',

    GET_NEWS: "GET_NEWS",
    SEARCH_SOURCES: "SEARCH_SOURCES",
    SEARCH_AUTHORS: "SEARCH_AUTHORS",
    SEARCH_CATEGORIES: "SEARCH_CATEGORIES",
    GET_SOURCES: "GET_SOURCES",
    LOAD_MORE_SOURCES: "LOAD_MORE_SOURCES",
    GET_AUTHORS: "GET_AUTHORS",
    LOAD_MORE_AUTHORS: "LOAD_MORE_AUTHORS",
    GET_CATEGORIES: "GET_CATEGORIES",
    LOAD_MORE_CATEGORIES: "LOAD_MORE_CATEGORIES"
}